chat_model:
  init_args:
    model: qwen3.6-plus
    model_provider: qwen
    # model: doubao-1-5-pro-32k-250115
    # model_provider: openai
    # api_key: 02e2f340-c72d-4d6c-9aba-43b21b037315
    # base_url: https://ark.cn-beijing.volces.com/api/v3
    # https://openrouter.ai/api/v1
  # Rate limits for chat model API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: 500
  max_requests_per_day: 2000

# image_generator:
#   class_path: tools.ImageGeneratorDoubaoSeedreamYunwuAPI
#   # tools.ImageGeneratorDashscopeQwenAPI
#   init_args:
#     api_key: 02e2f340-c72d-4d6c-9aba-43b21b037315
#     # base_url: https://ark.cn-beijing.volces.com/api/v3
#   # Rate limits for image generation API calls
#   # Set to null to disable rate limiting for this service
#   max_requests_per_minute: null
#   max_requests_per_day: null
image_generator:
  class_path: tools.ImageGeneratorComfyUIFlux
  init_args:
    base_url: http://192.168.3.4:8188
  # Rate limits for image generation API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: null
  max_requests_per_day: null

# video_generator:
#   class_path: tools.VideoGeneratorDoubaoSeedanceYunwuAPI
#   init_args:
#     api_key: 02e2f340-c72d-4d6c-9aba-43b21b037315
#   # Rate limits for video generation API calls
#   # Set to null to disable rate limiting for this service
#   max_requests_per_minute: null
#   max_requests_per_day: null
video_generator:
  class_path: tools.VideoGeneratorComfyUILTX
  init_args:
    base_url: http://192.168.3.4:8188
  # Rate limits for video generation API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: null
  max_requests_per_day: null

audio_generator:
  class_path: tools.AudioGeneratorComfyUIQwenTTS
  init_args:
    base_url: http://192.168.3.4:8188
  # Rate limits for video generation API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: null
  max_requests_per_day: null

working_dir: /Users/wangchangbin/ai/vimax_output6

# 中断步骤
## 汉字步骤
# crawl 爬取数据
# download 下载并转换字形图片
# idea 生成创意
# video 生成演变动画
## 正常流程步骤
# story 生成故事
# character 提取角色特征
# portrait 生成角色肖像
# script 生成剧本
# storyboard 生成故事板
# shot_description 生成镜头描述
# camera_tree 生成相机树
# camera_frame 生成相机帧
interrupt_step: null

# 模式
# normal 正常模式
# hanzi 汉字
# gacha 抽卡模式
mode: normal

gacha_config:
  # 抽卡类型
  # first_frame 首帧图片
  # last_frame 尾帧图片
  # video 视频
  type: video
  scene: 0
  shot: 2

hanzi: 日
