audio_generator:
  class_path: tools.AudioGeneratorComfyUIQwenTTS
  init_args:
    base_url: http://192.168.3.4:8188
  max_requests_per_day: null
  max_requests_per_minute: null
chat_model:
  init_args:
    model: qwen3.7-plus
    model_provider: qwen
  max_requests_per_day: 2000
  max_requests_per_minute: 500
comfyui_base_url: http://192.168.3.4:8188
gacha_config:
  scene: 1
  shot: 2
  type: last_frame
hanzi: 门
image_generator:
  class_path: tools.ImageGeneratorComfyUIFlux
  init_args:
    base_url: http://192.168.3.4:8188
  max_requests_per_day: null
  max_requests_per_minute: null
interrupt_step: idea
mode: hanzi
video_generator:
  class_path: tools.VideoGeneratorComfyUIMiniMax
  init_args:
    base_url: http://192.168.3.4:8188
  max_requests_per_day: null
  max_requests_per_minute: null
working_dir: /Users/wangchangbin/ai/vimax_men
